plugins:
  - prettier

extends:
  - prettier

parserOptions:
  ecmaVersion: 2017

rules:
  no-else-return: 2
  no-unused-vars: [2, {args: none}]
  prettier/prettier: [2, {
      bracketSpacing: false,
      printWidth: 80,
      singleQuote: true,
      trailingComma: es5
    }
  ]
