plugins:
  - prettier

extends:
  - prettier

parserOptions:
  ecmaVersion: 2017

rules:
  comma-dangle: [2, always-multiline]
  prettier/prettier: [2, {
      singleQuote: true,
      trailingComma: all,
      bracketSpacing: false
    }
  ]
